# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir M:/pc/Desktop/INF3430/Lab-1/Task-2/Task-2/Task-2.cache/wt [current_project]
set_property parent.project_path M:/pc/Desktop/INF3430/Lab-1/Task-2/Task-2/Task-2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib M:/pc/Desktop/INF3430/Lab-1/Task-2/decoder.vhd
read_xdc M:/pc/Desktop/INF3430/Lab-1/Task-2/Task-2/Task-2.srcs/constrs_1/new/constraints_decoder.xdc
set_property used_in_implementation false [get_files M:/pc/Desktop/INF3430/Lab-1/Task-2/Task-2/Task-2.srcs/constrs_1/new/constraints_decoder.xdc]

synth_design -top decoder -part xc7z020clg484-1
write_checkpoint -noxdef decoder.dcp
catch { report_utilization -file decoder_utilization_synth.rpt -pb decoder_utilization_synth.pb }
